Feat/week02-xml-challenge
NOW-SOPT-ANDROID/seyeong-kong pull request #17
Opened 2024-04-29 02:02 UTC by 0se0

## 작업 내용
- #16 **도전 과제**
- 유저 레포지토리 고쳐놨어요ㅎ 처음 하란 데로 하려고 해봤습니다!
- room DB 했어요(어려워요) 
- fake_repo_list 파일 깃허브꺼 받아온 거에서 제가 내용 더 넣어서 파싱했어요(어려워요)
- https://www.notion.so/sopt-official/katp-ksp-94768d0a0cc04906a2a089246703bb80 ㅋㅋ

## 구현 화면
https://github.com/NOW-SOPT-ANDROID/seyeong-kong/assets/121383083/834a63f0-06a2-4a46-9dcd-f16f360f3797

## 이슈
- 리스트가 (1,2,3,4,~)로 쌓이는 게 아니라 (2,3,4,~1)이렇게 쌓여요.
- 삭제하고 친구를 추가할 때 1번이나 2번을 삭제하고 추가를 하면 앱이 강제종료 돼요.
- 근데 1,2번이 아닌 다른 아이템을 삭제하고 추가하는 건 가능해요.

https://github.com/NOW-SOPT-ANDROID/seyeong-kong/assets/121383083/1b596ae6-2d60-40b4-867c-60e6823daa35

2024-04-29 02:26 UTC, KwakEuiJin reviewed
세영님 항상 열심히 하는 모습 너무 보기좋습니다!! 2주차 도전과제도 고생하셨습니다 👍

2024-04-29 02:26 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/data/Friend/FriendDatabase.kt
> +        }
👏

2024-04-29 02:26 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/data/Sopt.kt
> +        userRepository = UserRepository(preferenceInstance)
오 레포지토리를 싱글톤으로 Application단에서 초기화 하는 이유가 무엇일까요?

2024-04-29 02:26 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/data/UserRepository.kt
>          return User(userId, password, nickname, mbti)
오 이런 구조면 필드 1개만 null이여도 전체 User 의 데이터가 null이 될 것 같은데요 혹시 의도하신 동작이실까요?! (전부 옵셔널한 필드가 아닌건지)

만일 추후 옵셔널한 필드가 발생한다면 유연성을 위해서 모든 필드를 null혹은 empty하게 받아서 각 뷰마다 처리해주는 게 좋은 구조가 될 것 같습니다

다만 id, pw 의 경우에는 null이면 전체가 null인게 안전할 것 같습니다. 굳!

2024-04-29 02:26 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/data/UserRepository.kt
>      }
현재 apply() 메소드를 사용하여 비동기적으로 데이터를 저장하고 있는데, 이 방식은 다음 코드가 실행될 때 까지 데이터 저장이 완료되었는지 보장할 수 없습니다! 인증 관련 로직에서는 이런 불확실성이 문제를 일으킬 수 있을 것으로 예상되는데요 따라서, commit() 메소드를 사용하여 동기적으로 처리함으로써 데이터의 무결성을 확보하고, 다음 로직이 실행되기 전에 저장이 완료되었는지 확실히 할 필요가 있을 것 같습니다 ㅎ.ㅎ

다만 ANR의 위험성도 고려해야겠죠?!

2024-04-29 02:26 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/ui/home/FriendViewHolder.kt
>      }
제가 꿀팁공유에 적은 ViewHolder내에서 clickListener 처리하는 부분을 확인해보아도 좋을 것 같아요!

2024-04-29 02:26 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/ui/home/HomeFragment.kt
> +    }
와우 👍 viewLifecycleOwner를 사용하신 이유가 무엇인지도 남겨주면 만점!

2024-04-29 02:26 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/ui/home/HomeViewModel.kt
> +class HomeViewModel(application: Application) : AndroidViewModel(application) {
오 ㅋㅋㅋㅋㅋ 저 AndroidViewModel 은 첨봤어요 얘는 수명주기가 혹시 Application 주기를 따라가나요 한번 찾아봐야겠네요

2024-04-29 02:26 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/data/Sopt.kt
>      override fun onCreate() {
이름을 SoptApplication 이렇게 하는게 안헷갈릴 것 같습니다, 그리구 data패키지에 있으면 안될 것 같아요!!! root 경로에 있는게 알맞을 것 같습니다

2024-04-29 02:26 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/ui/search/SearchFragment.kt
> +
어댑터도 Context를 가지고 내부에서 동작하기 때문에 Fragment의 전역 변수로 선언할려면 onDestroyView에서 해제해주어야 할 것 같아요 ㅎㅎ

2024-04-29 02:26 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/ui/search/SearchFragment.kt
> +            }
use 사용 아주 좋아요

2024-04-29 02:26 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/ui/search/SearchFragment.kt
> +            }
요거 json파일 가져와서 viewModel로 던져서 viewModel에서 파싱 처리하는게 UI, Data 로직 분리 차원에서 더 좋아보입니다

2024-04-29 03:36 UTC, Sangwook123 requested changes
세영아 진짜 짱이다

2024-04-29 03:36 UTC, Sangwook123 commented on app/src/main/java/com/sopt/now/data/Friend/AppContainer.kt
> +}
여기서 의존성을 한번에 관리하는 방식 좋습니다 ! 다만 repository객체를 변수에 담고 있는 방식보다는 의존성을 제공하는 방법을 정의한 함수로 만드는 편이 어떤가요? 추후 관리 해야 할 의존성들이 많아질 경우 AppContainer인스턴스가 무거워질 것 같습니다.

2024-04-29 03:36 UTC, Sangwook123 commented on app/src/main/java/com/sopt/now/data/Sopt.kt
> +        userRepository = UserRepository(preferenceInstance)
현재 SharedPreferences객체를 싱글톤으로 관리해주고 있기때문에, 레포지토리는 굳이 싱글톤으로 구현하지 않아도 될 것 같습니다. AppContainer에 추가해도 좋을 것 같아요

2024-04-29 03:36 UTC, Sangwook123 commented on app/src/main/java/com/sopt/now/data/Friend/Friend.kt
> +    @PrimaryKey(autoGenerate = true) val id: Int,
id는 autogenerate니까 기본값 0으로 설정해주시면 됩니다 !

2024-04-29 03:36 UTC, Sangwook123 commented on app/src/main/java/com/sopt/now/ui/home/HomeFragment.kt
> +                        id = viewModel.friends.value?.size ?: (0 + 1),
id는 primary key에 autogenerate로 설정되어있으니까 id 값은 안 넘겨줘도 될 것 같습니다. 아마 앱이 종료된 것도 고유키가 충돌나서 그런 것 같아요

2024-04-29 03:36 UTC, Sangwook123 commented on app/src/main/java/com/sopt/now/ui/home/HomeViewModel.kt
> +    private val friendsRepository: FriendsRepository = AppContainer(application).friendsRepository
AppContainer객체를 초기화하기 위해서 application 컨텍스트가 필요해서 AndroidViewModel을 사용하신 것 같습니다. 

뷰모델 내부에서 friendRepository를 사용하기 위해서 AppContainer를 생성해 직접 참조하는 방식을 사용하고 계신데, AppContainer와 같은 의존성 컨테이너는 여러 곳에서 참조할 수 있도록 보통 앱의 생명주기와 동일하게 싱글톤으로 관리하는 것이 일반적입니다 ! 

또한 뷰모델에서 필요한 외부 의존성들은, 필드에서 직접 생성하는게 아니라 생성자 주입방식을 통해 외부에서 주입받아 사용하는 것이 보다 객체지향스럽고, 유지보수와 확장에 용이합니다.

FriendRepository를 직접 생성하는 방식말고, 뷰모델의 생성자로 받아주고 뷰모델 팩토리를 활용하시는 것을 추천드립니다!

2024-05-02 16:42 UTC, 0se0 commented on app/src/main/java/com/sopt/now/data/UserRepository.kt
>      }
헠.. 노란 줄이 다 나쁜 건 아니였군여....🧐

2024-05-02 16:55 UTC, 0se0 commented on app/src/main/java/com/sopt/now/ui/home/HomeFragment.kt
> +    }
Fragment 수명주기에 맞춰 LiveData 변화를 관찰하기 위해서요~>~!

2024-05-03 01:32 UTC, unam98 commented on app/src/main/res/layout/dialog_add_friend.xml
> +        app:layout_constraintTop_toTopOf="parent" />
나중에 프로덕트 만들면서 EditText를 쓸 땐 inputType이랑 최대 글자수, 후략 처리 등을 어떻게 할지 기획/디자인 파트와 논의하면서 진행해보면 좋을 것 같아용

2024-05-08 05:39 UTC, 0se0 commented on app/src/main/res/layout/dialog_add_friend.xml
> +        app:layout_constraintTop_toTopOf="parent" />
ㅋㅎㅋㅎ이번주 합세때 도전해보겠씀당

2024-05-08 09:12 UTC, Sangwook123 requested changes

2024-05-08 09:12 UTC, Sangwook123 commented on app/src/main/java/com/sopt/now/ui/home/HomeViewModelFactory.kt
> +        return viewModelFactory { HomeViewModel(application) }.create(modelClass)
지금 application을 생성자에 주입하고 있는데 그럴 필요없이 생성자에 repository를 주입하면 되지 않을까요?

2024-05-08 09:12 UTC, Sangwook123 commented on app/src/main/java/com/sopt/now/ui/home/HomeViewModel.kt
> +    private val appContainer: AppContainer = AppContainer(application.applicationContext)
appcontainer가 새로 초기화 되고있네요 !

2024-05-08 09:50 UTC, merged