Feat/week04-xml
NOW-SOPT-ANDROID/seyeong-kong pull request #20
Opened 2024-05-03 09:41 UTC by 0se0

## 작업 내용
- #18 필수 과제
- 레포지토리는 week02 챌린지에서 변경해놓을게요!
- 에러 메시지가 잘 안 받아져 와서 에러 바디를 문자열로 가져와서 넣었어요.
- 룸 한 거 버리기 아까워서 마이페이지에 팔로워 텍스트 버튼으로 api 목록 구현했어요 ㅎ
- 파일이 너무 많아져서 파일명이 비슷한 것끼리 일단 패키지로 묶었어요.

## 구현 화면

https://github.com/NOW-SOPT-ANDROID/seyeong-kong/assets/121383083/a6505b7c-b0c9-4b14-a1ea-19b164222f80

## 이슈
- 비밀번호를 바꾸고 나면 스낵바에 아이디가 null로 나오는 게 맞을까요?

2024-05-05 11:05 UTC, t1nm1ksun commented
고생하셨습니다!

2024-05-05 12:36 UTC, twogarlic commented on app/src/main/java/com/sopt/now/ui/follower/FollowerAdapter.kt
> +}
저도 follower  다시 시도해봐야겠네요 ㅠ

2024-05-05 12:40 UTC, twogarlic reviewed
수고하셨습니다 !

2024-05-05 13:27 UTC, Sangwook123 requested changes
고생하셨습니다 !

2024-05-05 13:27 UTC, Sangwook123 commented on app/src/main/java/com/sopt/now/ui/ch_password/ChPasswordFragment.kt
> +class ChPasswordFragment : Fragment() {
baseFragment 만들어서 각 프래그먼트마다 공통되는 부분 추상화 시켜도 좋을 것 같아요

2024-05-05 13:27 UTC, Sangwook123 commented on app/src/main/java/com/sopt/now/network/HeaderInterceptor.kt
> +class HeaderInterceptor(private val userRepository: UserRepository) : Interceptor {
인터셉터 사용 굿입니다👍

2024-05-05 13:27 UTC, Sangwook123 commented on app/src/main/java/com/sopt/now/ui/ch_password/ChPasswordViewModel.kt
> +    val liveData = MutableLiveData<AuthState>()
변수명 좀 더 알맞게 바꿔볼 수 있을 것 같아요

2024-05-05 13:27 UTC, Sangwook123 commented on app/src/main/java/com/sopt/now/ui/login/LoginViewModel.kt
> +                    val error = JSONObject(rawJson).optString("message", "error message")
kotlinx serialization 활용해봐도 좋을 것 같습니다

2024-05-05 13:27 UTC, Sangwook123 commented on app/src/main/java/com/sopt/now/ui/mypage/MypageViewModel.kt
> +                        userLiveData.postValue(it)
postValue를 사용하신 이유가 무엇인가요?

2024-05-07 01:57 UTC, KwakEuiJin reviewed
세영님 4주차 과제도 고생 많으셨습니다 ㅎㅎ

2024-05-07 01:57 UTC, kez-lab commented on app/src/main/java/com/sopt/now/data/UserRepository.kt
> +
특정 로그인 preferences로 로그인 여부를 판단하고 로그아웃하기보다는 모든 preferences를 clear하는게 더 좋을 것 같습니다.

예를 들어 preferences에 이름을 저장해뒀는데 로그아웃 이후에도 이름이 남아있는 문제가 발생할 수 잇을 것 같아서요!

2024-05-07 01:57 UTC, kez-lab commented on app/src/main/java/com/sopt/now/data/UserRepository.kt
>      }
preferences ktx를 활용하면 의도하신 람다로 처리가 더욱 쉬울 것 같습니다!
참고 링크: https://velog.io/@kej_ad/Kotlin-KTX를-이용한-SharedPreferences-활용하기

2024-05-07 01:57 UTC, kez-lab commented on app/src/main/java/com/sopt/now/network/HeaderInterceptor.kt
> +        return chain.proceed(newRequest)
default_member_id 의 경우 에러가 명시적으로 발생할 걸 대비하고 추가적인 처리가 필요할 것 같습니다

2024-05-07 01:57 UTC, kez-lab commented on app/src/main/java/com/sopt/now/network/service/AuthService.kt
> +
함수명이 chPassword 라면 어떤 기능을 하는 함수인지 헷갈릴 것 같습니다~!! 조금 더 명시적인 이름으로 만들어주시면 좋을 것 같습니다 ㅎㅎ

2024-05-07 01:57 UTC, kez-lab commented on app/src/main/java/com/sopt/now/ui/ch_password/ChPasswordFragment.kt
> +            viewModel.chPassword(RequestChPwDto(previousPassword = pre, newPassword = new, newPasswordVerification = verify))
RequestChPwDto를 Activity에서 만들게 되면 Dto의 변경이 Activity의 변경에 영향을 줄 것 같습니다, 차라리 파라메터로 넘긴 후 ViewModel에서 혹은 또 다른 데이터를 관리하는 영역에서 (레포지토리 패턴을 사용한다는 가정하에 예를 들면 데이터 레이어의 레포지토리의 구현체) DTO를 만드는 것은 어떨까요?

2024-05-07 01:57 UTC, kez-lab commented on app/src/main/java/com/sopt/now/ui/ch_password/ChPasswordViewModel.kt
> +            }
성공과 실패시 각각 기능을 함수로 분리하면 가독성측면에서 더욱 좋을 것 같습니다 ㅎㅎ

2024-05-07 01:57 UTC, kez-lab commented on app/src/main/java/com/sopt/now/ui/follower/FollowerFragment.kt
> +
followerAdapter도 결국 recyclerView와 결합되어있고 View 객체(item layout 등)를 소유하고 있기 때문에 binding 이 해제되는 시점에 같이 해제해주는 것이 메모리 측면에서 효율적입니다

2024-05-07 01:57 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/ui/login/LoginViewModel.kt
> +                    Sopt.userRepository.setMemberId(memberId)
MemberId같은 값을 싱글톤으로 저장하기 보다는 로컬에 저장하는게 어떨까요? 애플리케이션 수명주기가 종료된 이후에 다시 해당 변수를 불러오기 위해 불필요한 API 통신이 필요할 수 있을 것 같습니다.

2024-05-07 01:57 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/ui/mypage/MypageViewModel.kt
> +                        userLiveData.postValue(it)
null 일경우 처리가 필요할 것 같습니다!

2024-05-07 11:55 UTC, t1nm1ksun commented on app/src/main/java/com/sopt/now/ui/ch_password/ChPasswordViewModel.kt
> +                    val memberId = response.headers()["location"]?: "unknown"
그러게요 이렇게 했는데 왜 unknown이 아니라 null이라고 뜰까요...?

2024-05-07 11:55 UTC, t1nm1ksun commented on app/src/main/java/com/sopt/now/network/response/ResponseDto.kt
> +data class ResponseDto(
회원가입, 로그인, 비밀번호 변경은 응답하는 데이터 클래스 구조가 똑같은데 저는 왜 바보같이 3개나 만들었을까요... ㅎㅎ

2024-05-07 11:55 UTC, t1nm1ksun commented on app/src/main/java/com/sopt/now/ui/ch_password/ChPasswordViewModel.kt
> +    val liveData = MutableLiveData<AuthState>()
데이터들을 따로 만들어둔 AuthState로 관리하면 편하군요!

2024-05-09 05:39 UTC, 0se0 commented on app/src/main/java/com/sopt/now/ui/mypage/MypageViewModel.kt
> +                        userLiveData.postValue(it)
오.. 이거 네트워크 요청이여서 백그라운드 작업이라고 생각해서 postValue 사용했는데 setValue로 해도 잘 돌아가네요,,
onResponse가 메인이여서 그렇겠죠..? setValue로 하는 것이 더 나은 것인가요?

2024-05-09 05:46 UTC, 0se0 commented on app/src/main/java/com/sopt/now/data/UserRepository.kt
>      }
블로그ㅋㅋㅋㅋ 코드랩 주신 줄 알았어요

2024-05-09 06:17 UTC, 0se0 commented on app/src/main/java/com/sopt/now/network/HeaderInterceptor.kt
> +        return chain.proceed(newRequest)
이거 그냥 throw로 에러 날려도 되나요?

2024-05-09 10:54 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/ui/login/LoginViewModel.kt
> +                    Sopt.userRepository.setMemberId(memberId)
이거 제가 잘못남겼어요!!!

2024-05-09 10:56 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/ui/ch_password/ChPasswordViewModel.kt
> +                    val memberId = response.headers()["location"]?: "unknown"
memberId 를 초기화 하는 곳 여기!!
여기서는 memberId를 서버에서 안주고 있어서 unknown으로 들어갈겁니다

2024-05-09 11:00 UTC, 0se0 commented on app/src/main/java/com/sopt/now/ui/ch_password/ChPasswordViewModel.kt
> +                    val memberId = response.headers()["location"]?: "unknown"
ㅎㅎ체고~>~ 감사합니당

2024-05-09 11:01 UTC, 0se0 commented on app/src/main/java/com/sopt/now/ui/ch_password/ChPasswordViewModel.kt
> +                    val memberId = response.headers()["location"]?: "unknown"
서버에서 비밀번호 바꿀 때 memberId를 전해주지 않는가봐요!!

2024-05-09 17:08 UTC, merged