Feat/week04-compose
NOW-SOPT-ANDROID/seyeong-kong pull request #21
Opened 2024-05-03 10:14 UTC by 0se0

## 작업 내용
- #19 필수
- 기존 xml에서 했던 똑같은 방법으로 구현했어요.
- 네비게이션 파일 분리 시켜봤어요!

## 구현 화면

https://github.com/NOW-SOPT-ANDROID/seyeong-kong/assets/121383083/c7b04bc0-42cb-44b7-bffe-06bc1d6dba4e

## 이슈
비밀번호 변경 후에 로그인 하고 난 다음 다시 비밀번호 변경하려고 하면 화면이 막 혼자 움직여요;;ㅋㅎㅋ
상태 관리를 어떻게 해주어야 하는건가요🥶
-> 메인액티비티에서 뷰모델을 전달하는 것이 아닌 각 스크린에서 뷰모델을 생성해서 하니까 되는 거 같아요!

https://github.com/NOW-SOPT-ANDROID/seyeong-kong/assets/121383083/efb09ef9-b920-4dd9-9c66-b850714b19ae

## 기타
https://developer.android.com/develop/ui/compose/animation/customize?hl=ko
애니메이션 이거 봤어요!

2024-05-05 10:33 UTC, t1nm1ksun commented
고생하셨습니다~!

2024-05-05 13:54 UTC, twogarlic reviewed
수고하셨습니당

2024-05-05 14:03 UTC, l2hyunwoo requested changes
안녕하세요 세영님. 안드로이드 파트 명예 OB 이현우입니다. 만나서 반갑습니다.

앞으로의 과제들에 대한 코드리뷰를 맡게 되었습니다. 고민해보시다가 궁금한 점이 있으시면 지식 공유방/디스코드 연락 해주세요. 대면/비대면 자유형식으로 추가 피드백 가능합니다.

우선 과제 어려우셨을텐데 빠르게 과제 수행해주신점 너무 좋습니다. 관련해서 추가적으로 피드백/질문 남긴 것들이 있습니다. 질문을 남긴 경우 코드에 문제가 있어서 질문이 남긴 것이 아니고 정말 세영님의 작성 의도가 궁금해서 남긴 것이니 이 점 참고해주시면 감사하겠습니다.

추가로, Side Effect나 State 활용을 잘 해주셔서 코드 리뷰할 때 굉장히 인상적으로 봤습니다. 빠르게 성장하시는 모습 정말 보기 좋습니다. 한번 도전해볼만한 과제로는 서버통신 쪽 코드(enqueue)를 더 단축할 수 있는 코드 설계를 직접 구상해보시면 좋을 것 같아요. (코루틴/Rx 방식 제외)

앞으로 잘 부탁드리겠습니다.

2024-05-05 14:03 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/data/UserRepository.kt
> +        preferences.edit().putBoolean("isLoggedIn", loggedIn).commit()
```suggestion
        preferences.edit(commit = true) {
            it.putBoolean("isLoggedIn", loggedIn)
        }
```

- preferences-ktx 활용하시면 이렇게 적을 수도 있습니다.
- commit을 활용하신 이유가 있을까요?

2024-05-05 14:03 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/data/UserRepository.kt
>              apply()
여기엔 왜 apply를 적용하셨죠?

2024-05-05 14:03 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/data/UserRepository.kt
> +    }
로그아웃된 유저라면 앱 재접속 시에 해당 유저에 대한 정보는 없어야 할 것 같은데, 현재 로직대로라면 기기 내에 이전 유저의 정보는 저장되어있겠네요.

2024-05-05 14:03 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/network/HeaderInterceptor.kt
> +class HeaderInterceptor(private val userRepository: UserRepository) : Interceptor {
UserRepository는 아마 AuthService를 참조받을거고, AuthService는 ApiFactory에서 만들어진 레트로핏을 사용할거고, 그 레트로핏은 다시 HeaderInterceptor를 참조하는데 이건 다시 UserRepository를 참조하고 있네요? 

![image](https://github.com/NOW-SOPT-ANDROID/seyeong-kong/assets/54518925/47008b4d-b555-4852-b5a8-e0e9162c94ac)


지금 당장은 문제가 되지 않을 수 있지만, 이런 구조는 차후에 순환 참조 문제를 발생시킬 수 있어요. 어떻게 수정해야할지 한번 고민해보시면 좋을 것 같아요.

2024-05-05 14:03 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/network/reponse/ResponseFollowerDto.kt
> +) {
지금 당장은 문제될 일이 없겠지만, 나중에 앱 출시 직전에 SerialName을 안 붙인 프로퍼티들은 난독화대상이 될 수 있습니다. 이 부분 때문에 디버깅 안되는 에러 발생할 수 있으니 SerialName 어노테이션은 다 붙이는걸 권장드립니다.

2024-05-05 14:03 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/network/reponse/ResponseFollowerDto.kt
> +    )
Inner class 형식 좋습니다.

2024-05-05 14:03 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/ch_password/ChPasswordScreen.kt
> +fun ChPasswordScreen(navController: NavController) {
ChPassword -> ChangePassword

축약어는 지양해주세요. 코드리뷰시 타인이 컨텍스트를 모를 수 있습니다.

2024-05-05 14:03 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/ch_password/ChPasswordScreen.kt
> +    var verifyPw by remember { mutableStateOf("") }
축약어 지양해주세요.

2024-05-05 14:03 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/ch_password/ChPasswordScreen.kt
> +    val authState by viewModel.liveData.observeAsState()
👍🏻

2024-05-05 14:03 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/ch_password/ChPasswordScreen.kt
> +    }
👍🏻 전 이런식으로 nullable 떨어지는게 싫어서 뷰모델에서도 MutableState 쓰거나 MutableStateFlow 쓰긴 합니다.

2024-05-05 14:03 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/ch_password/ChPasswordScreen.kt
> +                ),
이거 Next누르면 다음 키보드로 이동하나요?

2024-05-05 14:03 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/ch_password/ChPasswordScreen.kt
> +            CustomBtn(
```suggestion
            CustomButton(
```

- 축약어 지양해주세요
- Cusotm이라고 하면 어떤 것이 떠오르시나요? 모호한 용어는 소통을 모호하게 만듭니다. 어떤 특성을 가진 버튼인지 좀 더 정확히 적어주면 좋을 것 같아요. 단 디자인 시스템 컴포넌트에 정의된 버튼이다 라고 하시면 {프로덕트이름}{컴포넌트 이름}으로 보통 적더라구요.

Ex) [SoptampButton](https://github.com/sopt-makers/sopt-android/blob/develop/feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/button/SoptampButton.kt)

2024-05-05 14:03 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/ch_password/ChPasswordScreen.kt
> +                MaterialTheme.colorScheme.primary,
```suggestion
                color = MaterialTheme.colorScheme.primary,
```

named argument 빼먹으신 것 같아요

2024-05-05 14:03 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/ch_password/ChPasswordViewModel.kt
> +    private val authService by lazy { ServicePool.authService }
lazy로 받아오신 이유가 있을까요?

2024-05-05 14:03 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/ch_password/ChPasswordViewModel.kt
> +    val liveData = MutableLiveData<AuthState>()
이 역시 liveData라고 하면 어떤 상태인지 타 개발자들은 그 의미를 찾아야 하는 경우가 많습니다. 이 부분 유의해주세요.

2024-05-05 14:03 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/follower/FollowerScreen.kt
> +    val followers = viewModel.followers.collectAsState().value
```suggestion
    val followers by viewModel.followers.collectAsStateWithLifecycle()
```

- by 사용하는게 가독성에 더 좋을 것 같습니다.
- collectAsState와 collectAsStateWithLifecycle의 차이는 뭘까요?

2024-05-05 14:03 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/login/LoginScreen.kt
> +                popUpTo("login") { inclusive = true }
이 부분 위에 있는 LaunchedEffect에 통합시킬 수 있지 않을까요?

2024-05-05 14:03 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/login/LoginScreen.kt
> +    var inputPw by remember { mutableStateOf(user?.password ?: "") }
```suggestion
    var inputId by remember { mutableStateOf(user?.id.orEmpty()) }
    var inputPw by remember { mutableStateOf(user?.password.orEmpty()) }
```

2024-05-05 14:03 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/login/LoginScreen.kt
> +    val user = SoptApp.userRepository.getUserData()
getUserData가 서버통신의 경우 해당 서버통신이 LoginScreen이 보여지는 단 한번만 호출되는 보장이 있을까요?

2024-05-05 14:03 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/mypage/MypageScreen.kt
> +            val (userImg, userNickname, follower, userPhone, userId, chPw, logout) = createRefs()
ConstraintLayout 사용하셨군요! 시도 좋습니다.

2024-05-05 14:03 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/mypage/MypageScreen.kt
> +                        }
```suggestion
                        navController.navigate("chPassword") {
                            popUpTo("mypage") { inclusive = true }
                        }
```

2024-05-05 14:03 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/mypage/MypageScreen.kt
>                          navController.navigate("login")
로그아웃하고 무조건 로그인 화면으로 넘어가는 것보다 결과를 받고 넘어가는게 과연 맞는 로직일까요? 데이터 삭제로직은 I/O 작업이고 해당 작업은 언제나 성공할 보장이 없습니다.

2024-05-05 14:03 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/mypage/MypageViewModel.kt
> +    fun info() {
함수명이 info면 어떤 함수인지 컴포즈 뷰를 보는 다른 개발자들이 알 수 있을까요?

2024-05-05 14:03 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/mypage/MypageViewModel.kt
> +    val userLiveData = MutableLiveData<UserInfo>()
MutableLiveData는 외부에서 변경하지 않도록 backing property를 운영하는 것이 컨벤션입니다.

2024-05-05 14:03 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/navigation/NavGraph.kt
> +    }
👍🏻

2024-05-05 14:03 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/navigation/NavGraph.kt
> +    }
추가) 해당 변수를 좀 더 안전하게 보관하려면 어떻게 해야할까요?

2024-05-06 13:22 UTC, 0se0 commented on app/src/main/java/com/sopt/now/compose/data/UserRepository.kt
> +        preferences.edit().putBoolean("isLoggedIn", loggedIn).commit()
apply()가 다음 코드가 실행될 때 까지 데이터 저장이 완료 되었는지 보장할 수 없다는 피드백을 받아 commit() 활용했습니다!

2024-05-06 13:27 UTC, 0se0 commented on app/src/main/java/com/sopt/now/compose/data/UserRepository.kt
>              apply()
setUserLoggedIn과는 달리 데이터가 바로 반영되지 않아도 된다고 생각해서 apply() 사용했습니다!

2024-05-06 13:30 UTC, 0se0 commented on app/src/main/java/com/sopt/now/compose/network/HeaderInterceptor.kt
> +class HeaderInterceptor(private val userRepository: UserRepository) : Interceptor {
ㅜㅜ 비둘기 코드였군여.. 
memberId를 저장해서 사용하고 싶어서 이렇게 짰는데 그 부분은 생각하지 못했습니당.. 수정해보도록 하겠습니다!

2024-05-06 13:46 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/data/UserRepository.kt
> +        preferences.edit().putBoolean("isLoggedIn", loggedIn).commit()
👍🏻

2024-05-06 13:48 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/data/UserRepository.kt
>              apply()
네 좋습니다. 그렇다면 바로 반영되어야 한다, 반영되지 않아도 된다는 세영님만의 기준을 따로 가지고 계시는건가요?

2024-05-06 13:54 UTC, 0se0 commented on app/src/main/java/com/sopt/now/compose/data/UserRepository.kt
>              apply()
오.. 기준이라기보다 commit()을 사용한 코드의 경우에는 반환 값이 있었기 때문이였고, 이 코드에서는 반환 값이 없어서 apply()를 사용했습니다!

2024-05-07 11:55 UTC, t1nm1ksun commented on app/src/main/java/com/sopt/now/compose/ui/ch_password/ChPasswordScreen.kt
> +    Scaffold(
SncakbarHost를 활용하기 위해서 Scaffold를 사용하신건가요? 아니면 다른 장점이 있어서 Scaffold를 사용하신건지 궁금합니다!

2024-05-07 11:55 UTC, t1nm1ksun commented on app/src/main/java/com/sopt/now/compose/ui/ch_password/ChPasswordViewModel.kt
> +class ChPasswordViewModel: ViewModel() {
뷰 모델로 따로 빼서 관리하는게 더 좋군요!

2024-05-10 03:51 UTC, 0se0 commented on app/src/main/java/com/sopt/now/compose/ui/ch_password/ChPasswordScreen.kt
> +                ),
넵!!

2024-05-10 05:39 UTC, 0se0 commented on app/src/main/java/com/sopt/now/compose/ui/ch_password/ChPasswordViewModel.kt
> +    private val authService by lazy { ServicePool.authService }
세미나에서 한 코드를 그대로 사용한 것이긴 한데, 
lazy가 한번만 초기화 되기도 하고, 필요할 때 초기화 시킬 수 있으니 장점을 가질 수 있다고 생각합니다!

2024-05-10 06:02 UTC, 0se0 commented on app/src/main/java/com/sopt/now/compose/ui/follower/FollowerScreen.kt
> +    val followers = viewModel.followers.collectAsState().value
오..!
collectAsStateWithLifecycle 얘는 Composable 생명주기에 따라서 작동해서 포그라운드일 때만 state 업데이트를 해주고, collectAsState는 포그라운드가 아니여도 state가 계속 업데이트 됩니다!

2024-05-10 10:39 UTC, 0se0 commented on app/src/main/java/com/sopt/now/compose/ui/ch_password/ChPasswordScreen.kt
> +    Scaffold(
ㅎㅎ전 주 코드에서 스낵바를 위로 올려놔서 Scaffold가 주는 이점이 없긴 하지만.. 이미 다른 코드에서 Scaffold로 다 해놔서 여기도 그렇게 했슴니당.. ㅎㅎ

2024-05-10 10:45 UTC, 0se0 commented on app/src/main/java/com/sopt/now/compose/ui/navigation/NavGraph.kt
> +    }
ㅜㅜ 이 부분 어떻게 해결해야 할 지 모르겠습니다! 
로그인이 된 인증상태이기 때문에 안전하게 보관해야 한다는 것 일까요?

2024-05-10 14:52 UTC, l2hyunwoo approved these changes
고생많으셨습니다. 빠르게 사항들 반영했네요 👍🏻

2024-05-10 14:52 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/change_password/ChangePasswordScreen.kt
> +package com.sopt.now.compose.ui.change_password
패키지/폴더 네이밍 컨벤션은 최대한 단일 단어로, 만약에 단일단어가 안된다면 camelCase로 바꿔주세요!

2024-05-10 14:52 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/home/HomeScreen.kt
> +
애니메이션 좋은 시도입니다.

2024-05-11 23:53 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/ui/navigation/NavGraph.kt
> +    }
안전하게....라기 보단 startDestination 대입 연산을 덜 하게 하는 방법에 관련된 것입니다.

2024-05-24 11:44 UTC, 0se0 commented on app/src/main/java/com/sopt/now/compose/ui/change_password/ChangePasswordScreen.kt
> +package com.sopt.now.compose.ui.change_password
넵!! 감사합니다~

2024-05-24 12:08 UTC, merged