week01_xml_challenge
NOW-SOPT-ANDROID/seyeong-kong pull request #7
Opened 2024-04-07 11:33 UTC by 0se0

## 작업내용
#2 week01_xml 도전과제 및 심화과제 포함

## 구현화면

https://github.com/NOW-SOPT-ANDROID/seyeong-kong/assets/121383083/b4b1e03f-e885-482a-8a0c-e85fc5e479ba

2024-04-08 13:36 UTC, Sangwook123 requested changes
심화, 도전까지.. 폼 미쳤다

2024-04-08 13:36 UTC, Sangwook123 commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +        val sharedPreferences = getSharedPreferences("SaveLogin", MODE_PRIVATE)
sharedPreferences를 새로 초기화해주신 이유가 뭘까요?

2024-04-08 13:36 UTC, Sangwook123 commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +        val password = sharedPreferences.getString("Password", "")
sharedpreferences에서 사용되는 기능들을 따로 클래스화 시켜주는 것도 좋아보입니다.

2024-04-08 13:36 UTC, Sangwook123 commented on app/src/main/java/com/sopt/now/MainActivity.kt
> +        getSharedPreferences("SaveLogin", MODE_PRIVATE)
이 함수가 실행 될 때마다 매번 객체 생성이 될 것 같습니다. 더 나은 방법이 없을까요? 앱 전역에서 sharedpreferences의 객체를 한개만 사용하는 방법이 있을 것 같습니다.

2024-04-08 13:36 UTC, Sangwook123 commented on app/src/main/java/com/sopt/now/SignupActivity.kt
> +    private fun observeFormValidation() {
옵저버 패턴 이용하신거 굿입니다 👍👍

2024-04-08 13:36 UTC, Sangwook123 commented on app/src/main/java/com/sopt/now/Extension.kt
> +inline fun <reified T : Parcelable> Intent.getParcelableExtraProvider(identifierParameter: String): T? {
inline함수는 어떻게 실행 될까요?

2024-04-08 15:46 UTC, 0se0 commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +        val sharedPreferences = getSharedPreferences("SaveLogin", MODE_PRIVATE)
삭제한다는 걸,, 까먹었어요..😓

2024-04-08 15:47 UTC, 0se0 commented on app/src/main/java/com/sopt/now/Extension.kt
> +inline fun <reified T : Parcelable> Intent.getParcelableExtraProvider(identifierParameter: String): T? {
함수가 호출되지 않고, 함수 본문 코드가 바로 실행됩니다!

2024-04-11 08:38 UTC, KwakEuiJin reviewed
심화과제까지!! 열정 최고!!

2024-04-11 08:38 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +    }
함수 순서에 이유가 있을까욥?!

2024-04-11 08:38 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +    }
요거 뭔가 ViewModel로 뺄 수 있을 것 같아요 저장 기능의 View의 책임은 아니니까요!

2024-04-11 08:38 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +    }
Context땜에 힘들 수 있지만 repository로 Data 단에서 Application Context를 참조한 Shared를 가져온다면 가능할듯요!

2024-04-11 08:38 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/SharedPreferences.kt
> +
요런 하드코딩보단 상수가 전역적으로 안전하게 쓰이기 좋을 것 같습니다~!!
Nickname이다가 다른 액티비티에서는 nickName으로 참조하면 값이 없다고 생각될거에요

2024-04-11 08:38 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/SignupActivity.kt
> +            )
변수 할당 혹은 함수를 사용하면 가독성을 조금 더 올릴 수 있을 것 같아요

2024-04-11 08:38 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/SignupViewModel.kt
> +        }
요렇게 넘기면 이전 State가 사라질 것 같아욥 data class의 copy라는 걸 알아보면 좋을 것 같습니다

2024-04-11 08:38 UTC, KwakEuiJin commented on app/src/main/java/com/sopt/now/SignupActivity.kt
> +                    finish()
요런 분기처리까지 ViewModel에서 완료하고 View는 데이터들고 이동만 하는 로직이 가능할 것 같아요 ViewModel을 데이터를 안전하게 저장하는 방법 외에도 이런 비즈니스 로직을 모두 처리하는 용도로 사용해보면 더 좋을 것 같습니다

2024-04-12 13:54 UTC, 0se0 commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +    }
먼저 실행될 거 같은 애들 순서대로 했습니다!

2024-04-20 07:32 UTC, merged